version: "3.4"
services:
    jekyll:
        image: jekyll/jekyll:latest
        command: jekyll serve --force_polling -w -I
#         --limit_posts 5
        ports:
            - 4000:4000
        volumes:
            - .:/srv/jekyll