version: "3.4"
services:
    jekyll:
        image: jekyll/jekyll:3.8.5
        command: jekyll serve --force_polling
        ports:
            - 4000:4000
        volumes:
            - .:/srv/jekyll